const express = require('express');
const router = express.Router();
const apiController = require('../app/controllers/apiController.js');
router.get('/', apiController.home);
router.get('/profile/:id', apiController.profile);
router.post('/upload-avatar/:id', apiController.uploadAvatar);
router.get('/course/search', apiController.courseSearch);
router.get('/course/:slug', apiController.showCourse);
router.post('/course/enroll/:courseId', apiController.enrollCourse);
router.post('/save-progress', apiController.saveProgress);
router.get('/get-progress/:userId/:courseId', apiController.getProgress);
router.get('/get-progress-user/:userId', apiController.getProgressUser);
router.get('/model', apiController.getmodelClassifier);
module.exports = router;
